### PR TITLE
Update VSPackage.resx

### PR DESCRIPTION
**Pull request by engunneer**
WildernessLabs/Meadow_Issues#418

### CODE REVIEW

**Comment by CartBlanche** [comment]
@engunneer thanks for this fix.

**Review by CartBlanche — APPROVED** [review]
LGTM

**Comment by engunneer** [comment]
@CartBlanche, as an aside, I can't fully build because of references to Mono.Debugging. What else do I need to install to build this? There are other issues I considered looking in to, but got stuck there.

**Comment by CartBlanche** [comment]
@engunneer The dependency is on the Xamarin stack, which they now call ".NET Multiplatform App UI Development" (rolls off the tongue). We eventually want to remove that dependency and have it work similar to how the VSCode extension handles debugging.  Do you have experience with VS Extension development?

**Comment by engunneer** [comment]
No, not directly. I learn by trying to fix small issues, or at least by stepping through code to see how it ticks. The issue about not deploying to a connected f7 when targeting desktop seemed interesting to learn about. Thanks for the heads up on what dependency I was missing. I managed to not need it for regular meadow work, so haven't installed the whole workflow. I'm surprised VS and Google both didn't tell me that I needed it.

**Pull request merged**
